[package]
name = "muestra"
version = "0.1.0"
authors = ["Enrique RP Buendia Lozada"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_distr="0.3.0"
rand="0.7.3"
num="0.3.0"